CREATE TABLE brands (
	id INT NOT NULL PRIMARY KEY,
	name_brand varchar(255) NULL,
	);

CREATE TABLE cars (
	id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
	brand_id INT,
	name_car varchar(255) NULL,
	price INT,
	 CONSTRAINT fk_cars_brands
        FOREIGN KEY (brand_id) REFERENCES brands (id)
	);

CREATE TABLE city (
	id INT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
	name_city varchar(255) NULL,
	population INT
	);